name:                CSE230-Final-Path-Tracer
version:             0.1.0.0
github:              "githubuser/CSE230-Final-Path-Tracer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/CSE230-Final-Path-Tracer#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- linear
- repa == 3.4.1.4
- mtl
- parsec

library:
  source-dirs: src

executables:
  CSE230-Final-Path-Tracer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSE230-Final-Path-Tracer

tests:
  CSE230-Final-Path-Tracer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CSE230-Final-Path-Tracer
